@startuml
'https://plantuml.com/activity-diagram-beta
skin rose

start
:User executes delete session command;
if () then ([Person index given is a positive integer])
    if () then (Day/time format given is valid])
        if () then ([Person index given is not larger than list size])
            if () then ([Person referenced is student])
                if () then ([Session given exists])
                    :Create new student with session deleted;
                    :Update contact list with new student created;
                    :Notes user that session has been deleted for the student;
                else ([else])
                    :Show error message that notes session nonexistence;
                endif
            else ([else])
                :Show error message that notes such command is only for students;
            endif
        else ([else])
            :Show error message that notes index provided is invalid;
        endif
    else ([else])
        :Show error message that notes invalid formatting of day/time;
    endif
else ([else])
    :Show "Invalid command format" error message;
endif
stop

@enduml
